server:
  port: 7010

eureka:
  instance:
    appname: accounts
    hostname: 206.81.15.0
    prefer-ip-address: false


management.security.enabled: false

endpoints:
  enabled: true
  sensitive: false
  restart:
    enabled: false
  pause:
    enabled: false
  refresh:
    enabled: false

database:
  jdbc-driver: org.postgresql.Driver
  url: jdbc:postgresql://206.81.15.0:5432/demo
  user: postgres
  password: sample

